# usage:
# docker compose -f postgres-db.yml up --build
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
